base:
  project: phone_pred_mlops
  random_state: 5398
  target_col: price_range


data_source:
  local_path: "phone_pred_dataset.csv"

split:
  dir: data/split
  train_file: train.csv
  test_file: test.csv
  split_ratio: 0.2

process:
  dir: data/processed
  train_file: final_train.csv
  test_file: final_test.csv


train:
  n_est: 55


model_dir: model
